### ISSUE TITLE
How agressively should we hunt source of pypi.io -> pypi.org 301 and pypi.org -> files.pythonhosted.org 301 redirect.

### ISSUE THREAD

**Issue by Carreau** [pypi/infra#176]
I [recently realized](https://github.com/conda-forge/conda-smithy/pull/2104/) that many of the conda-forge recipe point to pypi.io,  and that

```
https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ ext}}
```

 1) Redirect to `https://pypi.org/...` which itself 
 2) Redirect to `https://files.pythonhosted.org/...`

2 questions:

 - How much should we work on not having links to `pypi.io` ? That is to say how aggressively should we update recipes to point to pypi.org, or emit errors/warning message.
 - same for pypi.org, if we can directly update code to reach for `https://files.pythonhosted.org/...` url, how aggressively should we try to do it.

**Comment by miketheman** [comment]
Hi @Carreau ! I took a look today, and found that 3xx redirects for pypi.org-service is larger than the 2xx responses - almost by 40% - that happen at the edge provider (Fastly).

Since this is handled at the edge and the traffic rarely gets all the way to the backend, it hasn't been super bothersome to manage, rather the experience is seen by clients having to perform yet another DNS lookup, TLS exchange, etc etc.

The guidance surfaced in https://docs.pypi.org/api/#predictable-urls is probably what you want, and if you're already constructing URLs, there's no reason you'd need to also ask `pypi.org` for that to get a redirect to `files.pythonhosted.org`

**Comment by Carreau** [comment]
Thanks; I was also in particular thinking that at some point in the future you may want to retire `pypi.io`, but is there are that amny redirect; we are far from it.

**Comment by miketheman** [comment]
At some point in the future, yes, nothing on the radar right now, but it's best to update references to the correct endpoints, and thus save clients from redirects, and shed some load from the CDN.

**Comment by miketheman** [comment]
@Carreau I also forgot that there's a tracking issue for this, follow along for updates https://github.com/pypi/warehouse/issues/16800
